# Generated by Django 2.1 on 2018-08-19 10:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveOdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('bookmaker', models.CharField(choices=[('bet365', 'bet365'), ('bwin', 'bwin'), ('888sport', '888sport'), ('williamhill', 'williamhill')], max_length=15)),
                ('full_time_result', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('draw_no_bet', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('both_teams_to_score', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('double_chance', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('under_over', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
            options={
                'db_table': 'api_active_odds',
                'default_related_name': 'odds',
            },
        ),
        migrations.CreateModel(
            name='AllOdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('bookmaker', models.CharField(choices=[('bet365', 'bet365'), ('bwin', 'bwin'), ('888sport', '888sport'), ('williamhill', 'williamhill')], max_length=15)),
                ('full_time_result', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('draw_no_bet', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('both_teams_to_score', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('double_chance', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('under_over', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
            options={
                'db_table': 'api_all_odds',
                'default_related_name': 'all_odds',
            },
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('full_time_result', 'full_time_result'), ('draw_no_bet', 'draw_no_bet'), ('both_teams_to_score', 'both_teams_to_score'), ('double_chance', 'double_chance'), ('under_over', 'under_over')], max_length=20, null=True)),
                ('value', models.CharField(choices=[('1', '1'), ('X', 'X'), ('2', '2'), ('12', '12'), ('1X', '1X'), ('X2', 'X2'), ('over', 'over'), ('under', 'under'), ('yes', 'yes'), ('no', 'no')], max_length=5, null=True)),
                ('status', models.BooleanField(default=None, null=True)),
                ('odd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.AllOdd')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('country', models.CharField(max_length=100)),
                ('league', models.CharField(max_length=100)),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('home_goals', models.IntegerField(null=True)),
                ('away_goals', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'api_events',
                'ordering': ('datetime',),
            },
        ),
        migrations.AddField(
            model_name='allodd',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_odds', to='api.Event'),
        ),
        migrations.AddField(
            model_name='activeodd',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odds', to='api.Event'),
        ),
    ]
