# Generated by Django 2.2.4 on 2019-08-05 22:41

from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllOdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('bookmaker', models.CharField(choices=[('bet365', 'bet365'), ('bwin', 'bwin'), ('888sport', '888sport'), ('williamhill', 'williamhill')], max_length=15)),
                ('full_time_result', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('draw_no_bet', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('both_teams_to_score', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('double_chance', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('under_over', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
            options={
                'db_table': 'api_all_odds',
                'default_related_name': 'all_odds',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('country', models.CharField(max_length=100)),
                ('league', models.CharField(max_length=100)),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('home_goals', models.IntegerField(null=True)),
                ('away_goals', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'api_events',
                'ordering': ('datetime',),
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('money', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('note', models.TextField(blank=True, default='')),
                ('status', models.NullBooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_coupons',
            },
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('full_time_result', 'full_time_result'), ('draw_no_bet', 'draw_no_bet'), ('both_teams_to_score', 'both_teams_to_score'), ('double_chance', 'double_chance'), ('under_over', 'under_over')], max_length=20)),
                ('option', models.CharField(choices=[('1', '1'), ('X', 'X'), ('2', '2'), ('12', '12'), ('1X', '1X'), ('X2', 'X2'), ('over', 'over'), ('under', 'under'), ('yes', 'yes'), ('no', 'no')], max_length=5)),
                ('value', models.FloatField(default=None, null=True)),
                ('status', models.NullBooleanField()),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='api.Coupon')),
                ('odd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='api.AllOdd')),
            ],
            options={
                'db_table': 'api_bets',
                'default_related_name': 'bets',
            },
        ),
        migrations.AddField(
            model_name='allodd',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_odds', to='api.Event'),
        ),
        migrations.CreateModel(
            name='ActiveOdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('bookmaker', models.CharField(choices=[('bet365', 'bet365'), ('bwin', 'bwin'), ('888sport', '888sport'), ('williamhill', 'williamhill')], max_length=15)),
                ('full_time_result', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('draw_no_bet', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('both_teams_to_score', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('double_chance', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('under_over', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odds', to='api.Event')),
            ],
            options={
                'db_table': 'api_active_odds',
                'default_related_name': 'odds',
            },
        ),
    ]
