# Generated by Django 2.1 on 2018-08-19 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('money', models.FloatField()),
                ('note', models.TextField(default='')),
                ('status', models.BooleanField(default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_coupons',
            },
        ),
        migrations.AddField(
            model_name='bet',
            name='option',
            field=models.CharField(choices=[('1', '1'), ('X', 'X'), ('2', '2'), ('12', '12'), ('1X', '1X'), ('X2', 'X2'), ('over', 'over'), ('under', 'under'), ('yes', 'yes'), ('no', 'no')], default=None, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bet',
            name='odd',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.AllOdd'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bet',
            name='type',
            field=models.CharField(choices=[('full_time_result', 'full_time_result'), ('draw_no_bet', 'draw_no_bet'), ('both_teams_to_score', 'both_teams_to_score'), ('double_chance', 'double_chance'), ('under_over', 'under_over')], default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bet',
            name='value',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterModelTable(
            name='bet',
            table='api_bets',
        ),
        migrations.AddField(
            model_name='bet',
            name='coupon',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Coupon'),
            preserve_default=False,
        ),
    ]
