# Generated by Django 2.1 on 2018-08-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180819_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
