# Generated by Django 2.1 on 2018-08-20 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180819_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='api.Coupon'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='odd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='api.AllOdd'),
        ),
    ]
