# Generated by Django 2.1 on 2018-08-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180820_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
